server:
  port: 8001

spring:
  application:
    name: warehouse-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/springcloud_warehouse?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: sc_warehouse
    password: 20020725llt
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 600000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl