server:
  port: 8002

spring:
  application:
    name: delivery-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/springcloud_warehouse?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: sc_warehouse
    password: 20020725llt
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 600000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis:
  mapperLocations: classpath:mapper/*.xml